spring.application.name=rollbasedlogin
server.port=8080
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/rolebased_login?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:YOUR_GMAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD:YOUR_GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

weather.api.key=${WEATHER_API_KEY:59f598e860733fb19ae67d1813bd2f6d}

twilio.account.sid=${TWILIO_ACCOUNT_SID:YOUR_TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN:YOUR_TWILIO_AUTH_TOKEN}
twilio.phone.number=${TWILIO_PHONE_NUMBER:YOUR_TWILIO_PHONE_NUMBER}
huggingface.token=${HUGGINGFACE_TOKEN:YOUR_HUGGING_FACE_TOKEN}
huggingface.url=https://api-inference.huggingface.co/models/google/flan-t5-large