spring.application.name=rollbasedlogin
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/rolebased_login?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_GMAIL_USERNAME
spring.mail.password=YOUR_GMAIL_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

weather.api.key=59f598e860733fb19ae67d1813bd2f6d 

twilio.account.sid=YOUR_TWILIO_ACCOUNT_SID
twilio.auth.token=YOUR_TWILIO_AUTH_TOKEN
twilio.phone.number=YOUR_TWILIO_PHONE_NUMBER
huggingface.token=YOUR_HUGGING_FACE_TOKEN
huggingface.url=https://api-inference.huggingface.co/models/google/flan-t5-large